Ignore junk metadata
I have an .epub file here that has a content.opf with

    <meta content="Adobe InDesign" name="generator" />
    <dc:title />
    <dc:creator />
    <dc:subject />
    <dc:description />
    <dc:publisher />
    <dc:date>2013-06-20</dc:date>
    <dc:source />
    <dc:relation />
    <dc:coverage />
    <dc:rights />

This results in an XML node with None in the text attribute, which ends
up with an EpubPublication with a title = None, which then causes the
Jinja template | sort(key='title') to fail with a

    TypeError: '<' not supported between instances of 'NoneType' and 'str'